### ISSUE TITLE
AssertionError: xcall utility replied unexpectedly on *both* stdout and stderr

### ISSUE THREAD

**Issue by KingOfSpades** [robwalton/python-xcall#3]
Great wrapper! I've been googleing something like this for dayz!

Quick problem. I'm using this wrapper to call Things3 on macOS but getting:

```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    xcall.xcall('things', 'add?title=Test')
  File "xcall.py", line 86, in xcall
    return client.xcall(action, action_parameters, activate_app)
  File "xcall.py", line 132, in xcall
    result = self._xcall(cmdurl, activate_app)
  File "xcall.py", line 167, in _xcall
    'Try xcall directly from terminal with: "%s" ' % (stdout, stderr, ' '.join(args)))
AssertionError: xcall utility replied unexpectedly on *both* stdout and stderr.
stdout: "b'{\n  "x-things-id" : "5588E4D4-53F6-4EB8-841F-411B3BED840D"\n}\n'"
stderr: "b''"
```

So the stange thin is. It works! The call is beging routed and the action is performd.

**Comment by KingOfSpades** [comment]
The code I'm using btw:

```python
import xcall

xcall.xcall('things', 'add?title=Test')
```
